version: '3'
services:
  app:
    build: 
      dockerfile: Dockerfile
      context: .
      target: development
    command: npm run dev
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:changeme123@db:5432/news_db
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
      - SESSION_SECRET=lkaflkdrwsgjnrfdkgnfjknbdfgvjkjnb
    depends_on:
      - db
      
  db:
    image: postgres:alpine
    volumes:
      - data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=news_db
      - POSTGRES_PASSWORD=changeme123
  
  redis:
    image: redis:alpine

volumes:
  data:
